{
  name = "selfnote"
  pages_build_output_dir = "./"
  "d1_databases": [
    {
      "binding": "selfnote_db",
      "database_name": "selfnote-db",
      "database_id": "9157d359-f157-47e6-97f6-f5fd047a9b16"
    }
  ]
}